# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'NYSE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYSE
  pod 'RealmSwift'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'SwiftSpinner'
  pod 'PromiseKit'

end
